- name: A playbook to deploy an image, create a service and scale a deployment on a VM
  hosts: localhost
  user: ubuntu
  become: no
  tasks:
  - name: 3.1. Create docker image deployment
    become: no
    shell:
        cmd: kubectl create deployment docker-kubernetes-cw2 --image=mselkirk/devopscoursework
  - name: 3.2. Create service
    become: no
    shell:
        cmd: kubectl expose deployment/docker-kubernetes-cw2 --type="NodePort" --port 80 --name node-port-service
  - name: 3.3. Scale Deployment
    become: no
    shell:
        cmd: kubectl scale deployments/docker-kubernetes-cw2 --replicas=4
